require 'image_processing/config'
require 'image_processing/downloader'
require 'image_processing/downsampler'
require 'image_processing/file_manager'
require 'image_processing/ftp_adaptor'
require 'image_processing/uploader'
