#!/bin/bash
#PBS -V
#PBS -l walltime=3:00:00
#PBS -l ncpus=8
#PBS -N colour_volume

cd $PBS_O_WORKDIR

export PROJECT_ROOT='/home/comp-card/mattgibb/registration'
export BIN_DIR="$PROJECT_ROOT/itk_release_sal"
export OUTPUT_DIR="$PROJECT_ROOT/results/Rat28/bottom_vessels/HiResPairs/AdjustedTransforms/CenteredAffineTransform_20"

# get unique list of slices
function image_list() {
  cat $PROJECT_ROOT/config/Rat28/image_lists/image_list.txt | uniq
}

# build each colour slice
mkdir $OUTPUT_DIR/HiRes_2

i=1
for slice in `image_list`; do
  $BIN_DIR/BuildColourVolume Rat28 bottom_vessels -L \
    --hiResTransformsDir HiResPairs/AdjustedTransforms/CenteredAffineTransform_20 \
    --slice $slice \
    --hiResName HiRes_2/`printf %03d $i`.tiff
  ((i++))
done

# reconstruct volume
$BIN_DIR/BuildVolumeFromSlices $((i-1)) $OUTPUT_DIR/{HiRes_2/%03d.tiff,HiRes.mha}
    
# split volumes into slices
for dim in 0 1; do
  $BIN_DIR/SplitVolumeIntoSlices $OUTPUT_DIR/{HiRes.mha,HiRes_$dim} -d $dim -e tiff --latex
done

echo "finished."
