#!/bin/bash
#PBS -V
#PBS -l walltime=3:00:00
#PBS -l ncpus=4:mem=13gb
#PBS -N default

# 4 cores per node on orac, so take total memory usage, divide by 12GB or 24GB, then multiply by 4
# total orac cores is 256?
# 1TB ram on orac
# use tracejob or date to time jobs
cd $PBS_O_WORKDIR
# date +%s > dates
echo "input: " $1
echo "output: " $2
echo "downsample_ratio: " $3
~/registration/itk_build/ShrinkImage $1 $2 $3
echo "finished."
# date +%s >> dates
