#!/bin/bash
#PBS -V
#PBS -l walltime=1:00:00
#PBS -l select=1:mpiprocs=8
#PBS -N build_volumes

cd $PBS_O_WORKDIR
~/registration/itk_build_sal/BuildVolumes $1 $2 $3
echo "finished."
# date +%s >> dates
