#!/bin/bash
#PBS -V
#PBS -l walltime=24:00:00
#PBS -l select=1:mpiprocs=8
#PBS -N build_volumes
#PBS -p 1023

# use tracejob or date to time jobs
cd $PBS_O_WORKDIR
# date +%s > dates
~/registration/itk_build_sal/BuildVolumes Rat24 BuildVolumes
echo "finished."
# date +%s >> dates
