#!/bin/bash
#PBS -V
#PBS -l walltime=0:10:00
#PBS -l select=1:mpiprocs=8
#PBS -N resample_bmp

cd $PBS_O_WORKDIR
~/registration/itk_build_sal/ResampleBMP $1 $2 $3 $4 $5
echo "finished."
# date +%s >> dates
