#!/bin/bash
#PBS -V
#PBS -l walltime=3:00:00
#PBS -l select=1:mpiprocs=8
#PBS -N default

# check out -l mem directive
# 4 cores per node on orac, so take total memory usage, divide by 12GB or 24GB, then multiply by 4
# total orac cores is 256?
# 1TB ram on orac
# use tracejob or date to time jobs
cd $PBS_O_WORKDIR
# date +%s > dates
~/registration/itk_build_sal/ShrinkImage \
  /export/home/comp-card/mattgibb/registration/images/Rat24/HiRes/originals/Rat24_0459.bmp \
  /export/home/comp-card/mattgibb/registration/images/Rat24/HiRes/downsamples_32/Rat24_0459.bmp \
  32
# date +%s >> dates

# from command line
# echo "~/registration/itk_build/ShrinkImage ~/registration/images/Rat24/LoRes-rgb/originals/0443.bmp ~/registration/images/Rat24/LoRes-rgb/downsamples_8/0443.bmp 8" | qsub -l ncpus=4:walltime=1:00:00 -N test
